{% set name = "gdptools" %}
{% set version = "0.0.25.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gdptools-{{ version }}.tar.gz
  sha256: cc1e6efdd355b341598093ce1f3f5b6f73387ea720300ebca27d84e2975c9f13

build:
  entry_points:
    - gdptools = gdptools.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6,<3.10
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.6,<3.10
    - pandas >=1.4.0
    - numpy >=1.21.0,<2.0.0
    - geopandas >=0.11.0
    - shapely >=1.8.1
    - pygeos >=0.12.0
    - pyproj >=3.3.0
    - metpy >=1.2.0
    - attrs >=21.4.0
    - pydantic >=1.9.0
    - xarray >=0.21.1
    # xarray[io]
    - netCDF4
    - h5netcdf
    - scipy
    - zarr
    - fsspec
    - cftime
    - rasterio
    - cfgrib
    - pooch
    # xarray[accel]
    - scipy
    - bottleneck
    - flox
    # xarray[parallel]
    # dask[complete]
    - dask

test:
  imports:
    - gdptools
  commands:
    - pip check
    - gdptools --help
  requires:
    - pip

about:
  home: https://code.usgs.gov/wma/nhgf/toolsteam/gdptools
  summary: Gdptools
  license: Unlicense
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - rmcd-mscb
    - ocefpaf
