{% set name = "gdptools" %}
{% set version = "0.2.18" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gdptools-{{ version }}.tar.gz
  sha256: f6d28869342447fee02fceebf48847367a1adfe32b74a61095a45b76656f98d6

build:
  entry_points:
    - gdptools = gdptools.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - bottleneck >=1.3.3
    - dask >=2022.0.0
    - dask-core >2024.8.0
    - dask-geopandas >0.4.1
    - fastparquet >=2024.2.0
    - geopandas >=0.13.0
    - geoviews >=1.12.0,<2.0.0
    - joblib >=1.4.0
    - metpy >=1.2.0
    - netcdf4 >=1.5.8
    - numpy >2.0
    - pandas >=2.0.0
    - pyarrow <18.1.1
    - pydantic >=1.10.5,<2.0.0
    - pydap >=3.2.2,<4.0.0
    - pyproj >=3.3.0
    - pystac >=1.10.0,<2.0.0
    - rasterio >=1.2.9,<1.5.0
    - rioxarray >=0.13.0
    - s3fs >=2025.2.0,<2026.0.0
    - scipy >=1.13.0,<2.0.0
    - shapely >=2.0
    - statsmodels >=0.14.0,<0.15.0
    - tqdm >=4.66.2,<5.0.0
    - urllib3 >=1.26.0,<2.0.0
    - xarray 2024.7.0
    - xpystac >=0.1.3,<0.2.0
    - zarr >=2.12.0
    # - attrs >=20.3,<22
    # - bump2version >=1.0.1,<2.0.0
    # - certifi <2023.7.22
    # - pygeos >=0.14.0,<0.15.0
    # xarray[io]
    - cfgrib
    - cftime
    - fsspec
    - h5netcdf
    # - pooch
    # xarray[accel]
    # - flox

test:
  imports:
    - gdptools
  commands:
    - pip check
    - gdptools --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://code.usgs.gov/wma/nhgf/toolsteam/gdptools
  summary: Gdptools
  license: Unlicense
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - rmcd-mscb
    - ocefpaf
