{% set name = "gdptools" %}
{% set version = "0.2.14" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gdptools-{{ version }}.tar.gz
  sha256: 482f162396e2c499140fd94ab4633e5fcc7b18b93f385c289032992f26c7d4dc

build:
  entry_points:
    - gdptools = gdptools.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    # - certifi <2023.7.22
    # - bump2version >=1.0.1,<2.0.0
    - geoviews >=1.12.0,<2.0.0
    - pystac >=1.10.0,<2.0.0
    - s3fs >=2024.3.1,<2025.0.0
    - urllib3 >=1.26.0,<2.0.0
    - xpystac >=0.1.3,<0.2.0
    - tqdm >=4.66.2,<5.0.0
    - statsmodels >=0.14.0,<0.15.0
    - dask-core >=2024.7.1,<2025.0.0
    - python >={{ python_min }}
    - fastparquet >=2024.2.0
    - pyarrow <17.0.0
    - dask-geopandas 0.4.1
    - pandas >=2.0.0
    - numpy <2.0
    - geopandas >=0.13.0
    - shapely >=2.0
    # - pygeos >=0.14.0,<0.15.0
    - pyproj >=3.3.0
    - metpy >=1.2.0
    # - attrs >=20.3,<22
    - pydantic >=1.10.5,<2.0.0
    - xarray >=2024.3.0
    - netcdf4 >=1.5.8
    - scipy >=1.13.0,<2.0.0
    - pydap >=3.2.2,<4.0.0
    - zarr >=2.12.0
    - rasterio >=1.2.9
    - bottleneck >=1.3.3
    - dask >=2022.0.0
    - joblib >=1.4.0
    - rioxarray >=0.13.0
    # xarray[io]
    - h5netcdf
    - fsspec
    - cftime
    - cfgrib
    # - pooch
    # xarray[accel]
    # - flox

test:
  imports:
    - gdptools
  commands:
    # Should work with shapely 1.8.5, we can remove this when there is a next release with revised pins.
    # - pip check
    - gdptools --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://code.usgs.gov/wma/nhgf/toolsteam/gdptools
  summary: Gdptools
  license: Unlicense
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - rmcd-mscb
    - ocefpaf
