{% set name = "gdptools" %}
{% set version = "0.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gdptools-{{ version }}.tar.gz
  sha256: 30028779b5424d0892c131b7042c1a30a56d46d395093b0a9749292f1af2d3c1

build:
  entry_points:
    - gdptools = gdptools.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.11
    - pip
    - poetry-core >=1.0.0
  run:
    - dask-core >=2022.0.0
    - python >=3.6,<3.11
    - pandas >=1.4.0
    - numpy <1.24.0
    - geopandas >=0.11.0
    - shapely <2.0.0
    - pygeos >=0.12.0
    - pyproj >=3.3.0
    - metpy >=1.2.0
    - attrs >=21.4.0
    - pydantic >=1.9.0
    - xarray >=2022.6.0
    - netcdf4 <=1.6.1
    - scipy >=1.9.0
    - pydap >=3.2.2,<4.0.0
    - zarr >=2.12.0
    - rasterio >=1.2.9
    - bottleneck >=1.3.3
    - dask >=2022.0.0
    - joblib >=1.1.0
    - rioxarray >=0.12.0
    # xarray[io]
    - h5netcdf
    - fsspec
    - cftime
    - cfgrib
    - pooch
    # xarray[accel]
    - flox

test:
  imports:
    - gdptools
  commands:
    - pip check
    - gdptools --help
  requires:
    - pip

about:
  home: https://code.usgs.gov/wma/nhgf/toolsteam/gdptools
  summary: Gdptools
  license: Unlicense
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - rmcd-mscb
    - ocefpaf
