{% set name = "gdptools" %}
{% set version = "0.0.24.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gdptools-{{ version }}.tar.gz
  sha256: f46c3826574689010cbe10d700abc03b5fee604f2a8b51730ca972b21e62fefa

build:
  entry_points:
    - gdptools = gdptools.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.10
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.6,<3.10
    # - click <8
    - click
    # - pygeoapi >=0.11.0,<0.12.0
    - pygeoapi
    - geopandas >=0.11.1,<0.12.0
    - shapely >=1.8.4,<2.0.0
    - pygeos >=0.13,<0.14
    - numpy >=1.23.2,<2.0.0
    # - dask-core >=2022.9.0,<2023.0.0
    - dask-core
    - pandas >=1.4.4,<2.0.0
    - xarray >=2022.6.0,<2023.0.0
    - netcdf4 >=1.6.0,<2.0.0
    - scipy >=1.9.1,<2.0.0
    - pydap >=3.2.2,<4.0.0
    - zarr >=2.12.0,<3.0.0
    - rasterio >=1.3.2,<2.0.0
    - rioxarray >=0.12.0,<0.13.0
    - pyproj >=3.3.1,<4.0.0
    - metpy >=1.3.1,<2.0.0
    - python-attr >=0.3.2,<0.4.0
    - attrs <22
    - pydantic >=1.10.2,<2.0.0

test:
  imports:
    - gdptools
  commands:
    # cannot run pip check b/c we are breaking the pins for dask, click, and pygeoapi.
    # - pip check
    - gdptools --help
  requires:
    - pip

about:
  home: https://code.usgs.gov/wma/nhgf/toolsteam/gdptools
  summary: Gdptools
  license: Unlicense
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - rmcd-mscb
    - ocefpaf
