{% set name = "gdptools" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gdptools-{{ version }}.tar.gz
  sha256: 8f49e51cf9525a0eb2a448ec9d834c3b282b82cf427a842e5919b3561d0d95b3

build:
  entry_points:
    - gdptools = gdptools.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<=3.11
    - pip
    - poetry-core >=1.0.0
  run:
    - certifi <2023.7.22
    - bump2version >=1.0.1,<2.0.0
    - python >=3.8,<=3.11
    - dask-core >=2022.0.0
    - fastparquet >=0.4.0
    - pyarrow >=1.0.1
    - dask-geopandas >=0.2.0
    - pandas >=1.4.0
    - numpy >=1.21
    - geopandas >=0.13.0
    - shapely >=2.0
    - pygeos >=0.14.0,<0.15.0
    - pyproj >=3.3.0
    - metpy >=1.2.0
    - attrs >=20.3,<22
    - pydantic <=1.10.9
    - xarray >=2022.6.0
    - netcdf4 >=1.5.8
    - scipy >=1.9.0
    - pydap >=3.2.2,<4.0.0
    - zarr >=2.12.0
    - rasterio >=1.2.9
    - bottleneck >=1.3.3
    - dask >=2022.0.0
    - joblib >=1.1.0
    - rioxarray >=0.12.0
    # xarray[io]
    - h5netcdf
    - fsspec
    - cftime
    - cfgrib
    - pooch
    # xarray[accel]
    - flox

test:
  imports:
    - gdptools
  commands:
    # Should work with shapely 1.8.5, we can remove this when there is a next release with revised pins.
    # - pip check
    - gdptools --help
  requires:
    - pip

about:
  home: https://code.usgs.gov/wma/nhgf/toolsteam/gdptools
  summary: Gdptools
  license: Unlicense
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - rmcd-mscb
    - ocefpaf
